### ISSUE TITLE
Implement 'up' and 'down' command, guide users to avoid 'convert'.

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/opencompose#153]
Since OpenCompose is a *higher* abstraction, we should guide users to use `opencompose up` and `opencompose down` rather than `opencompose convert`.

`opencompose convert` should be used as a _last_ resort in terms of converting to Kubernetes artifacts, rather than what's currently suggested.

**Comment by kadel** [comment]
I would rather use something else than up/down, but I agree with the general idea.

It was a low priority,  having usable language is more important right now.

**Comment by surajssd** [comment]
But for this I would directly call `kubectl` or `oc` commands underneath, because it's a huge pain to do `up` and `down` by ourselves. Let's use the binaries directly(since they are good at doing it).

And we can assume that for someone using a k8s cluster will have a kubectl binaries available locally.

**Comment by cdrage** [comment]
I'd vote the opposite and do direct API calls. But using kubectl directly is the best in terms of getting a POC out.

Otherwise, as @kadel said, more focusing on the usable language!

**Comment by kadel** [comment]
I would say that parsing output of kubectl commands is a much bigger pain.

With https://github.com/kubernetes/client-go everything got much easier.


But let's discuss this once we have a real need for this.
