### ISSUE TITLE
Provide shorter URL/command for installing from GitHub releases

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/opencompose#36]
Binaries on the release page should be binaries and not zip / tar.gz files.

**Comment by tnozicka** [comment]
@cdrage I don't think so, but we can discuss it. 

It dramatically reduces size in our case from ~36MB to ~5MB and the 2 biggest related projects do it this way:
 - https://github.com/kubernetes/kubernetes/releases
 - https://github.com/openshift/origin/releases

**Comment by cdrage** [comment]
Ah, just makes it *way* easier to simply curl the binaries.

Example: https://kubernetes.io/docs/user-guide/prereqs/

**Comment by kadel** [comment]
what if we put both there? binaries and archives?  everyone can choose.
Storage is free ;-)

**Comment by tnozicka** [comment]
Ok, I thought what was a different related project that is famous for making it simple and easy for developers to use and install? So I went and looked into [docker releases](https://github.com/docker/docker/releases) and all the binaries are archives, again. It seems to me like a pattern for GH releases.

> and not zip / tar.gz files.

@cdrage I don't agree at all with ditching archives (tars, zip) from our release page, but I don't oppose your idea of releasing binaries. Although IMO it is equivalently simple to install tar as it is to install the binary itself and it takes 14% of the time to download it. The issue is the the binary doesn't retain permission, but tar does. Let's go by example:

1) Install from tar:
(we document the syntax in [README](https://github.com/redhat-developer/opencompose/blame/master/README.md#L28))
```bash
curl -L https://.../opencompose-....tar.xz | tar -xJf - -C ${HOME}/bin ./opencompose
```

2) Install it from binary
```bash
curl -L https://.../opencompose-v...-linux-64bit > ${HOME}/bin/opencompose && chmod +x ${HOME}/bin/opencompose
```

Also if you are doing it in GUI like Nautilus, you don't have to change the permissions and just drag and drop the binary from the archive.

That said I am wiling to put binaries in our releases **in addition** to archives. I am just not convinced about a good enough reason to do so. As @kadel said storage is free and we can let users choose. 

But if we decide to do that, it won't be sooner that we get our CI to actually do the releases instead of doing it manually.

**Comment by cdrage** [comment]
Archives are automatically created by GitHub so it shouldn't be a problem with the addition of the binaries :) 

We should also be doing sha256 / encrypted signatures on the releases as well.

**Comment by tnozicka** [comment]
> Archives are automatically created by GitHub so it shouldn't be a problem with the addition of the binaries :)

I meant archives containing the binary. Those will stay.

**Comment by cdrage** [comment]
I'd suggest renaming the way you name archives as well as `curl -L https://github.com/redhat-developer/opencompose/releases/download/v0.1.0-alpha.0/opencompose-v0.1.0-alpha.0-d0edfd9-linux-64bit.tar.xz | tar -xJf - -C ${HOME}/bin ./opencompose` is a long command as it is..

Also, why is it going to ${HOME} ? Not /usr/local/bin/ ?

**Comment by cdrage** [comment]
Ex renaming to:
```
opencompose-darwin-amd64
opencompose-linux-amd64
opencompose-windows-amd64.exe
```

For each release.

**Comment by tnozicka** [comment]
@cdrage I don't wan't it to sound too harsh but if you want to change things give us a good reason to do so! Compare it to what naming convention we have, what are the advantages and disadvantages of the new naming and why we should adopt those. We are not gonna change it just because *"you like it this way"*. I went into a lot of detail and gave you references to why we have the current conventions at https://github.com/redhat-developer/opencompose/issues/36#issuecomment-282679129 and it also follows Kubernetes and OpenShift naming conventions https://github.com/redhat-developer/opencompose/issues/36#issuecomment-282378987 and I would expect you to do the same especially since you are the one proposing the change.

**Comment by cdrage** [comment]
@tnozicka 

Having a shorter name equals to a shorter command / cleaner command when installing. Although I do believe we should keep archives on the GitHub release page, we can utilize GitHub as a CDN when downloading the binaries instead of having it hosted elsewhere.

So essentially the best of both worlds, having tagged / encrypted signatured .tar.gz archives similar to long-running projects (such as openshift, libvirt) as well as having something similar to https://kubernetes.io/docs/user-guide/prereqs/ for downloading the actual binaries for easy-as-pie-installation.

The naming conventions are informative and great in terms of grabbing the *source*. Although having a quick guide to install-and-go it would be best to have a short url / naming convention for simplification.

Hopefully we can have a curl -o /usr/local/bin/opencompose https://opencompose.io/get/opencompose_linux_amd64 one day

**Comment by tnozicka** [comment]
@cdrage thanks for going into detail.

> Although I do believe we should keep archives on the GitHub release page, we can utilize GitHub as a CDN when downloading the binaries instead of having it hosted elsewhere.

Agreed.

> So essentially the best of both worlds, having tagged / encrypted signatured .tar.gz archives similar to long-running projects (such as openshift, libvirt) as well as having something similar to https://kubernetes.io/docs/user-guide/prereqs/ for downloading the actual binaries for easy-as-pie-installation.

Just to clarify on archives. There are 3 archives at this point that we create and support: opencompose-v0.1.0-alpha.0-d0edfd9-(linux,macos,windows)-64bit.(tar.xz,zip,zip). Whenever I said archives I meant those and they contain the opencompose binary, README.md and LICENSE. Then there are 2 with the source code itself not supported or created by our release but injected by GitHub and AFAIK can't be disabled. Disregard those.

> The naming conventions are informative and great in terms of grabbing the source. Although having a quick guide to install-and-go it would be best to have a short url / naming convention for simplification.

Yes, the are informative and having the version and git sha in their name prevents mishandling them when doing a release.

> Hopefully we can have a curl -o /usr/local/bin/opencompose https://opencompose.io/get/opencompose_linux_amd64 one day

If I get you correctly, and please correct me if I am wrong, the reason you want have binaries (and with simplified names) is to have a nice and short command to install opencompose.

Assuming it is the case here is my take on it:
 - I don't like having files in releases not named informatively and the way that also prevent misshandling. Also git tags (->releases) can be accidentally overwritten - that's why I like to have git sha in a release name - you know where it came from.
 - I like having a short command to install **latest** opencompose version. I just don't think GitHub releases are the way.

**Proposed solution**:
Leaving the releases as they are - How about we do something in terms of:
```bash
curl http://get.opencompose.io/ | sh
```
implemented as
```bash
curl -L https://github.com/redhat-developer/opencompose/releases/download/v0.1.0-alpha.0/opencompose-v0.1.0-alpha.0-d0edfd9-linux-64bit.tar.xz | tar -xJf - -C ${HOME}/bin ./opencompose
```
(actually doing zip on macOS and windows and changing paths)

That would have a benefit of both of our solutions
1) the speed of downloading 14% of the actual binary
2) nice and short command

@cdrage WDYT?

**Comment by tnozicka** [comment]
Although I don't mind the non-pretty download URL because majority of the people will just copy-paste it from README.

**Comment by cdrage** [comment]
@tnozicka Going forward with your proposal would be okay by me. Still concerned in regards to the `${HOME}/bin` path. I'm assuming that's a placeholder and will be different on the actual commands?

If you are having the binaries in .tar.gz's, I think similar to `oc`, we should download + untar ONLY the binary, not including the license, README, etc.

**Comment by tnozicka** [comment]
> Still concerned in regards to the ${HOME}/bin path. I'm assuming that's a placeholder and will be different on the actual commands?

I was also considering `/usr/local/bin` at that time but that requires elevated (admin) privileges. That's why I've put there $HOME/bin. Not ideal, maybe even *wrong* as I don't think it's in PATH by default. So at this point it's meant as a placeholder for user to replace if he wishes to do so.
I'll send a PR to replace the step with something in terms of:
```bash
curl -L https://github.com/redhat-developer/opencompose/releases/download/v0.1.0-alpha.0/opencompose-v0.1.0-alpha.0-d0edfd9-linux-64bit.tar.xz | tar -xJ ./opencompose
```
With `mv` being an *optional step*
```bash
sudo mv ./opencompose /usr/local/bin
```

If we go with `curl http://get.opencompose.io/ | sh` it get's complicated. You can't (or shouldn't) run such command as root. You may trust it as a regular user because as that user you still run our binary. But if someone intents to run opencompose binary only as a regular user he may not trust us enough to run the script with elevated privileges. We could actually just have the script so it creates opencompose binary in current directory and instruct user to `cd` to any directory and then move the binary with `sudo` to `/usr/local/bin/`. It just doesn't give us that much at that point. (See at the end for an alternative.)

> If you are having the binaries in .tar.gz's, I think similar to oc, we should download + untar ONLY the binary, not including the license, README, etc.

@cdrage We already do that. If you untar it according to steps in our README you get only the binary - that's the last argument to `tar` *"./opencompose"*.

But for the reasons above if we do not install the binary and require user to do so by `mv` we could also do:
```bash
curl -L https://get.opencompose.io/ | tar -xJ ./opencompose
```
```bash
sudo mv ./opencompose
```
That seems pretty easy and reasonable to me. All we need is an redirection service using GH releases as CDN doing redirection to lastest release URl (can be listed by github REST API) by issuing HTTP 307 to it. I can put something together in ~a day when there is time to do it.

**Comment by surajssd** [comment]
Talking about pretty URLs, the script can do something as checks on the OS and then put the binary in the user specific PATH directory.

For e.g. Fedora has `~/.local/bin` is under PATH, need to look at other distros. This won't need elevated permissions.
